//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BL.BusinessLogic.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} que intenta dar de alta, ya existe..
        /// </summary>
        internal static string EntityF_Error_AlredyExist {
            get {
                return ResourceManager.GetString("EntityF_Error_AlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar la {0}..
        /// </summary>
        internal static string EntityF_Error_Delete {
            get {
                return ResourceManager.GetString("EntityF_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la {0} solicitada..
        /// </summary>
        internal static string EntityF_Error_NotFound {
            get {
                return ResourceManager.GetString("EntityF_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo dar de baja la {0}..
        /// </summary>
        internal static string EntityF_Error_Terminate {
            get {
                return ResourceManager.GetString("EntityF_Error_Terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creada(s) satisfactoriamente..
        /// </summary>
        internal static string EntityF_Success_Created {
            get {
                return ResourceManager.GetString("EntityF_Success_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} ha sido borrada satisfactoriamente..
        /// </summary>
        internal static string EntityF_Success_Delete {
            get {
                return ResourceManager.GetString("EntityF_Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} modificada(s) satisfactoriamente..
        /// </summary>
        internal static string EntityF_Success_Updated {
            get {
                return ResourceManager.GetString("EntityF_Success_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} que intenta dar de alta, ya existe..
        /// </summary>
        internal static string EntityM_Error_AlredyExist {
            get {
                return ResourceManager.GetString("EntityM_Error_AlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar el {0}..
        /// </summary>
        internal static string EntityM_Error_Delete {
            get {
                return ResourceManager.GetString("EntityM_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el {0} solicitado..
        /// </summary>
        internal static string EntityM_Error_NotFound {
            get {
                return ResourceManager.GetString("EntityM_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creado(s) satisfactoriamente..
        /// </summary>
        internal static string EntityM_Success_Created {
            get {
                return ResourceManager.GetString("EntityM_Success_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} ha sido borrado satisfactoriamente..
        /// </summary>
        internal static string EntityM_Success_Delete {
            get {
                return ResourceManager.GetString("EntityM_Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} modificacio(s) satisdactoriamente..
        /// </summary>
        internal static string EntityM_Success_Updated {
            get {
                return ResourceManager.GetString("EntityM_Success_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo dar de baja el {0}..
        /// </summary>
        internal static string EntityM_Terminate {
            get {
                return ResourceManager.GetString("EntityM_Terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vacío. No se pudo obtener la información necesaria..
        /// </summary>
        internal static string EntiyM_Error_Empty {
            get {
                return ResourceManager.GetString("EntiyM_Error_Empty", resourceCulture);
            }
        }
    }
}
